export const route = {
  login: '/',
  forgotPassword: '/forgot-password',
  resetPassword: (token) => `/reset-password/${token}`,
  changePassword: '/change-password',
  editProfile: '/profile',
  dashboard: '/dashboard',
  adminManagement: '/admin-management',
  addAdmin: '/admin-management/add-admin',
  editAdmin: (id) => `/admin-management/edit-admin/${id}`,
  viewAdmin: (id) => `/admin-management/view-admin/${id}`,
  gameManagement: '/game-management',
  addGame: '/game-management/add-game',
  editGame: (id, type) => `/game-management/${type}-game/${id}`,
  packageManagement: '/package-management',
  addPackagePage: '/package-management/add-package',
  editPackagePage: (id, type) => `/package-management/${type}-package/${id}`,
  viewPackagePage: (id) => `/package-management/view-package/${id}`,
  featureManagement: '/feature-management',
  editFeaturePage: (id, type) => `/feature-management/${type}-feature/${id}`,
  subjectManagement: '/subject-Management',
  addSubjectPage: '/subject-Management/add-subject',
  inquiryManagement: '/inquiry-management',
  stageManagement: '/stage-management',
  addStage: '/stage-management/add-stage',
  editStagePage: (id, type) => `/stage-management/${type}-stage/${id}`,
  viewStagePage: (id, type) => `/stage-management/${type}-stage/${id}`,
  addQuestion: '/stage-management/add-question',
  editQuestionPage: (id, type) => `/stage-management/${type}-question/${id}`,
  viewQuestionPage: (id, type) => `/stage-management/${type}-question/${id}`,
  aboutusMangement: '/About-Us',
  subTopicManagement: '/sub-topic-management',
  privacypolicy: '/Privacy-Policy',
  termsandcondition: '/Terms-And-Condition'
}
